# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: zip
        uses: montudor/action-zip@v1.0.0
        with: 
          args: zip -qq -r cobblemon_rideon_custom_${{ steps.tag_version.outputs.new_tag }}.zip data pack.mcmeta
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: cobblemon_rideon_custom_${{ steps.tag_version.outputs.new_tag }}.zip
          bodyFile: cobblemon_rideon_custom_${{ steps.tag_version.outputs.new_tag }}.zip
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            username: krajetum_slave
            avatarUrl: https://media.forgecdn.net/avatars/thumbnails/620/286/64/64/638008832892634916.png
            footer: Non mi chiedete nuove mount pls.
            severity: info
            text: Una nuova versione del resource_pack rilasciata!
            description: Scaricate la versione aggiornata dal link (sbrigateve pure)
            details: https://github.com/krajetum/cobblemon_rideon/releases/tag/${{ steps.tag_version.outputs.new_tag }}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
